WITH INFORMATION AS (
    SELECT YEAR(SALES_DATE) AS YEAR
         , MONTH(SALES_DATE) AS MONTH
         , USER_ID
      FROM ONLINE_SALE
     GROUP BY YEAR, MONTH, USER_ID
)

SELECT YEAR
     , MONTH
     , GENDER
     , COUNT(*) AS USERS
  FROM USER_INFO A
     , INFORMATION B
 WHERE 1=1
   AND A.USER_ID = B.USER_ID
   AND GENDER IS NOT NULL
 GROUP BY YEAR, MONTH, GENDER
 ORDER BY YEAR, MONTH, GENDER
 ; 