WITH FRONTEND AS (
    SELECT SUM(CODE) AS VALUE
      FROM SKILLCODES
     WHERE CATEGORY = 'Front End'
)

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
  FROM DEVELOPERS A
     , FRONTEND B
 WHERE SKILL_CODE & VALUE > 0
 ORDER BY ID