WITH SKILL AS (
    SELECT SUM(CODE) AS VALUE
      FROM SKILLCODES
     WHERE CATEGORY = 'Front End'
)

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
  FROM SKILL A
     , DEVELOPERS B
 WHERE B.SKILL_CODE & A.VALUE != 0
 ORDER BY ID
 ;