WITH CAR AS (
    SELECT CAR_ID
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
     WHERE START_DATE >= '20220801'
       AND START_DATE < '20221101'
     GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)


SELECT MONTH(START_DATE) AS MONTH
     , A.CAR_ID
     , COUNT(*) AS RECORDS
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
     , CAR B
 WHERE A.CAR_ID = B.CAR_ID
   AND START_DATE >= '20220801'
   AND START_DATE < '20221101'
  GROUP BY MONTH, A.CAR_ID
 HAVING COUNT(*) > 0
 ORDER BY MONTH ASC, CAR_ID DESC
;